name: Tests

on:
  push:
    branches: '**'
    tags: '**'
  pull_request:
    branches: '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Build
      run: |
        docker build --tag nlp_build_test .
    - name: Test run
      run: |
        mkdir -p neuron-to-paper-nlp/output/out
        mkdir -p neuron-to-paper-nlp/output2
        mkdir -p neuron-to-paper-nlp/ontology
        docker run -v neuron-to-paper-nlp:/my_volume --env=DATA_FOLDER=/my_volume/output/out --env=OUTPUT_FOLDER=/my_volume/output2 --env=ONTOLOGY_FOLDER=/my_volume/ontology nlp_build_test
    
